version: '3.8'

services:
  market_place_db:
    image: mysql:latest
    container_name: market_place_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: market_place_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bridge_net


volumes:
  mysql_data:

networks:
  bridge_net: